summary: A command-line tool to help you insert the correct compiler options when compiling objects and/or linking libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2 
bin-url: https://github.com/leleliu008/uppm-package-repository-freebsd-14.0-amd64/releases/download/2025.07.22/pkg-config-0.29.2-freebsd-14.0-amd64.release.tar.xz 
bin-sha: d7c471ed8a046e50f77a74eaa45b8b8b556909ad9b09825787fafa969b4a263e
